# This file was generated by GoReleaser. DO NOT EDIT.
cask "kik" do
  version "0.19.0"

  on_macos do
    on_intel do
      sha256 "1612d957ff3cccda58745281b75137e5db9215ac107ee71f4f2dc356a654ba87"
      url "https://github.com/kikplate/kikplate/releases/download/v#{version}/kik-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/kikplate/kikplate/"
    end
    on_arm do
      sha256 "a213d4e38f47eac828a67bd112164bcb9179dc2004ff3a21e62f8517563867d1"
      url "https://github.com/kikplate/kikplate/releases/download/v#{version}/kik-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/kikplate/kikplate/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1345af98d79bd97fd775343c4053ba49aef5ab53fad0131a89caff5b3c17d981"
      url "https://github.com/kikplate/kikplate/releases/download/v#{version}/kik-#{version}-linux-amd64.tar.gz",
        verified: "github.com/kikplate/kikplate/"
    end
    on_arm do
      sha256 "3edb448efecad554f4fb998bbb211c13ad7e91e3e179731922e28c01e6765268"
      url "https://github.com/kikplate/kikplate/releases/download/v#{version}/kik-#{version}-linux-arm64.tar.gz",
        verified: "github.com/kikplate/kikplate/"
    end
  end

  name "kik"
  desc "Command-line interface for the Kikplate plate registry"
  homepage "https://github.com/kikplate/kikplate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kik"

  # No zap stanza required

  caveats <<~EOS
    If macOS blocks execution, run: xattr -dr com.apple.quarantine $(brew --prefix)/Caskroom/kik/*/kik
  EOS
end
