# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kikplate < Formula
  desc "Command-line interface for the Kikplate plate registry"
  homepage "https://github.com/kikplate/kikplate"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kikplate/kikplate/releases/download/v0.14.0/kikplate-0.14.0-darwin-amd64.tar.gz"
      sha256 "5630eef3d35d3dd2049176af7551eeaa907604b9bcf3678a7d43bfa184ead4c8"

      define_method(:install) do
        bin.install "kikplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kikplate/kikplate/releases/download/v0.14.0/kikplate-0.14.0-darwin-arm64.tar.gz"
      sha256 "5378d3a855e15147533c3cc1f88a8d63ebb1cec9811ef352c255fda180a6999f"

      define_method(:install) do
        bin.install "kikplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kikplate/kikplate/releases/download/v0.14.0/kikplate-0.14.0-linux-amd64.tar.gz"
      sha256 "50fb42eee78ffe65c978c81db6cbf862fac281b486f0d18ffd4ecd01d5b23983"
      define_method(:install) do
        bin.install "kikplate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kikplate/kikplate/releases/download/v0.14.0/kikplate-0.14.0-linux-arm64.tar.gz"
      sha256 "fd96b753314787266e04ca9485ca134f0a4fbd39087253517520f6a5163b6047"
      define_method(:install) do
        bin.install "kikplate"
      end
    end
  end
end
